### ISSUE TITLE
Questions, student requesting for help

### ISSUE THREAD

**Issue by misaka-10032** [catatnight/docker-postfix#1]
I'm trying to find a smtp server to send verification emails for my homework at college. I don't know if I come to the right place. I've built the image and have it run. I wonder if I need extra steps to have it send mails, for example DNS (actually I've tried this, still not work)?

I am using [flask-mail](https://pythonhosted.org/flask-mail/) to test. The message returned shows that authentication has been passed and that the mail has been queued, but, I still cannot receive the email. Here's the message, although by flask-mail, hopefully it can help:

send: 'ehlo [172.17.0.11]\r\n'
reply: '250-leggyleggy.com\r\n'
reply: '250-PIPELINING\r\n'
reply: '250-SIZE 10240000\r\n'
reply: '250-VRFY\r\n'
reply: '250-ETRN\r\n'
reply: '250-STARTTLS\r\n'
reply: '250-AUTH PLAIN LOGIN CRAM-MD5 DIGEST-MD5 NTLM\r\n'
reply: '250-AUTH=PLAIN LOGIN CRAM-MD5 DIGEST-MD5 NTLM\r\n'
reply: '250-ENHANCEDSTATUSCODES\r\n'
reply: '250-8BITMIME\r\n'
reply: '250 DSN\r\n'
reply: retcode (250); Msg: leggyleggy.com
PIPELINING
SIZE 10240000
VRFY
ETRN
STARTTLS
AUTH PLAIN LOGIN CRAM-MD5 DIGEST-MD5 NTLM
AUTH=PLAIN LOGIN CRAM-MD5 DIGEST-MD5 NTLM
ENHANCEDSTATUSCODES
8BITMIME
DSN
send: 'AUTH CRAM-MD5\r\n'
reply: '334 PDMxMTc5Njk5MjYuNzUyODYzM0BsZWdneWxlZ2d5LmNvbT4=\r\n'
reply: retcode (334); Msg: PDMxMTc5Njk5MjYuNzUyODYzM0BsZWdneWxlZ2d5LmNvbT4=
send: 'bm8tcmVwbHkgM2Q4MGQ3OGMwMWZhOWJjZDYxM2M2YjBhYjRjZjUzOTI=\r\n'
reply: '235 2.7.0 Authentication successful\r\n'
reply: retcode (235); Msg: 2.7.0 Authentication successful
send: u'mail FROM:no-reply@leggyleggy.com size=251\r\n'
reply: '250 2.1.0 Ok\r\n'
reply: retcode (250); Msg: 2.1.0 Ok
send: u'rcpt TO:longqicai@gmail.com\r\n'
reply: '250 2.1.5 Ok\r\n'
reply: retcode (250); Msg: 2.1.5 Ok
send: 'data\r\n'
reply: '354 End data with <CR><LF>.<CR><LF>\r\n'
reply: retcode (354); Msg: End data with <CR><LF>.<CR><LF>
data: (354, 'End data with <CR><LF>.<CR><LF>')
send: 'Content-Type: text/plain; charset="utf-8"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: 7bit\r\nSubject: hello\r\nFrom: no-reply@leggyleggy.com\r\nTo: longqicai@gmail.com\r\nDate: Mon, 24 Nov 2014 07:38:13 +0000\r\nMessage-ID: 20141124073807.18.73370@e5924df9bbf8\r\n\r\n.\r\n'
reply: '250 2.0.0 Ok: queued as 0B292585\r\n'
reply: retcode (250); Msg: 2.0.0 Ok: queued as 0B292585
data: (250, '2.0.0 Ok: queued as 0B292585')
send: 'quit\r\n'
reply: '221 2.0.0 Bye\r\n'
reply: retcode (221); Msg: 2.0.0 Bye

Thank you very much if you can help.

**Comment by catatnight** [comment]
These two suggestions may be helpful:
1. Configure SPF, DKIM, Reverse DNS correctly, pls refer to [3 DNS Records Every Email Marketer Must Know](http://www.rackaid.com/blog/email-dns-records/).
2. Take a look at the log file `/var/log/mail.log` in postfix container, which contains more information. (cmd: `sudo docker cp <container_id>:/var/log/mail.log . && sudo cat mail.log`)

**Comment by misaka-10032** [comment]
@catatnight , log is like this:

Nov 24 09:35:18 bd3f8c192e14 postfix/smtpd[136]: connect from unknown[172.17.0.14]
Nov 24 09:35:18 bd3f8c192e14 postfix/smtpd[136]: A3F5758B: client=unknown[172.17.0.14], sasl_method=CRAM-MD5, sasl_username=no-reply
Nov 24 09:35:18 bd3f8c192e14 postfix/cleanup[139]: A3F5758B: message-id=20141124093234.12.18805@cdb1b16406ae
Nov 24 09:35:18 bd3f8c192e14 postfix/qmgr[95]: A3F5758B: from=no-reply@leggyleggy.com, size=435, nrcpt=1 (queue active)
Nov 24 09:35:18 bd3f8c192e14 postfix/smtpd[136]: disconnect from unknown[172.17.0.14]

Nothing strange here. Maybe the ISP just reject the sending request? I've read the article. It seems I need to connect the ISP if I want to setup a email server? Private email servers without verification are not allowed for the sake of safety reasons? Please tell me if I understand it right. Thanks!

**Comment by catatnight** [comment]
@misaka-10032 log shows everything goes well with postfix.

So, you should do some tricks on your dns record for [leggyleggy.com](http://leggyleggy.com).
1. [create an SPF record](http://kb.mediatemple.net/questions/658/How+can+I+create+an+SPF+record+for+my+domain%3F#gs)
2. [Add public key](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-dkim-with-postfix-on-debian-wheezy#generate-the-public-and-private-keys) (The [introduction section](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-dkim-with-postfix-on-debian-wheezy#introduction) of this article may be helpful for you to understand why your outgoing mail is blocked.)

In addition, set rdns record for your mail server's ip address, which I think could be accomplished on the control panel of your server's provider.

**Comment by misaka-10032** [comment]
@catatnight , thanks a lot. You saved me a lot of trouble. Actually I still don't have the plan to publish it because it's just a micro-project homework at college. Your instructions are very helpful. I will reference them when I need to. Again, thank you very much!

**Comment by justforkidding** [comment]
@catatnight I am also not able to receive mail in my inbox
